---
title: "Comethyl promoters 1kb"
output: html_notebook
---

```{r}
library(Biobase)
library(comethyl)
library(GenomicRanges)
library(openxlsx)
library(dplyr)
library(tidyverse)
library(circlize)
library(ComplexHeatmap)
library(ggplot2)
library(ggbio)

setwd("C:\\Users\\fopa0001\\Downloads\\OneDrive_1_04-12-2023")

options(stringsAsFactors = FALSE)
Sys.setenv(R_THREADS = 1)
WGCNA::enableWGCNAThreads(nThreads = 4)


colData <- read.xlsx("pheno_comethyl.xlsx", rowNames = TRUE)
colData$Density[colData$Density>10000] <- 10000
colData <- colData %>% rename(Concentration = Density)

chr = read.table(file="chrom_list.txt",
                 header = F,
                 stringsAsFactors = F)

chr_list <- chr$V1

#bs <- getCpGs(colData, 
 #             path = "./",
  #            chroms = chr_list,
   #           file = "Unfiltered_BSseq.rds")


#bs <- filterCpGs(bs, cov = 10, perSample = 0.85, file = "Filtered_BSseq.rds")
bs <- readRDS("Filtered_BSseq.rds")
setwd("C:\\Users\\fopa0001\\Downloads\\OneDrive_1_04-12-2023")

### annotation file
bed <- read.table(file="Salpinus_promoters_1kb.gff",header=F,
                  sep="\t",
                  stringsAsFactors = F)

bed <- bed[,c(1,4,5)]

colnames(bed) <- c("chr","start","end")#,"type","what","how")

ac_annot <- makeGRangesFromDataFrame(bed,
                                     keep.extra.columns = F,
                                     ignore.strand = TRUE)


```

```{r}
# call regions
regions <- getRegions(bs,  
                      custom=ac_annot)


## filter regions
regions<- filterRegions(regions, covMin = 10, 
                         methSD = 0.1, 
                         file = "Filtered_Regions.txt")


```

```{r}
meth <- getRegionMeth(regions, 
                      bs = bs, 
                      file = "Region_Methylation.rds")

mod <- model.matrix(~1, data = pData(bs))

methAdj <- adjustRegionMeth(meth, 
                            PCs = mod,
                            file = "Adjusted_Region_Methylation.rds")

WGCNA::allowWGCNAThreads()
sft <- getSoftPower(methAdj,
                    blockSize = 10000,
                    corType = "pearson",
                    file = "Soft_Power.rds")

modules <- getModules(methAdj, 
                      power = sft$powerEstimate, 
                      regions = regions, 
                      corType = "pearson", 
                      file = "Modules.rds")


MEs <- modules$MEs

moduleDendro <- getDendro(MEs, distance = "pearson")


MEtraitCor <- getMEtraitCor(MEs, colData = colData[c(1:6,8:10)], corType = "pearson" ,file = "ME_Trait_Correlation_Stats_prom1kb.txt")
traitDendro <- getCor(MEs, y = colData[c(1:6,8:10)], corType = "pearson", robustY = FALSE) %>% getDendro(transpose = TRUE)

cor_matrix_prom <- as.matrix(with(MEtraitCor, tapply(cor, list(trait, module), mean)))
p_matrix_prom <- as.matrix(with(MEtraitCor, tapply(p, list(trait, module), mean)))

color_mapping <- colorRamp2(c(-0.7, 0, 0.7), c("salmon4", "white", "skyblue4"))


column_colors_prom <- colnames(cor_matrix_prom)
col_annotation_prom <- HeatmapAnnotation(df = data.frame(Module = column_colors_prom),
                                    col = list(Module = setNames(column_colors_prom, column_colors_prom)),
                                    show_legend = FALSE)

main_hm_prom <- Heatmap(cor_matrix_prom, col=color_mapping, bottom_annotation = col_annotation_prom, show_column_names = FALSE, 
                   cluster_rows = FALSE, cluster_columns = TRUE, 
                   row_split = c(rep("Growth", 2), rep("Sperm quality", 7)), row_gap = unit(3,"mm"),
                   heatmap_legend_param = list(title="Cor"), 
                   cell_fun = function(j, i, x, y, w, h, fill){
                     if(p_matrix_prom[i, j] < 0.05/ncol(p_matrix_prom)) {
                       grid.text("*", x, y)
                       }
                     })

main_hm_prom
```
```{r}
colors <- as.character(unique(MEtraitCor$module))

sig_regions <- MEtraitCor[MEtraitCor$p < 0.05/ncol(MEs) & MEtraitCor$module!="grey",1:2]
sig_regions <- inner_join(sig_regions,modules$regions, by="module")
sig_regions <- sig_regions[grep("NC", sig_regions$chr),]

genome <- read.table("//wsl.localhost/Ubuntu/home/fotis/analysis/Genome/Salvelinus_hybrid/ncbi_dataset/data/GCF_002910315.2/GCF_002910315.2_ASM291031v2_genomic.fna.fai", header = F)
genome$start <- 1
genome <- genome[grep("NC", genome[,1]),]
genome <- genome[genome[,1] != "NC_000861.1",]

genome <- genome[,c(1,6,2)]
names(genome) <- c("chr","start","end")
genome$chr <- as.character(genome$chr)
genome$LG <- paste0("LG",c(1,2,3,"4p","4q.1:29","4q.2",5,"6.1","6.2",seq(7,28),seq(30,37)))

sig_regions <- inner_join(sig_regions, genome[,c(1,4)], by="chr")
sig_regions$chr <- sig_regions$LG
genome$chr <- genome$LG

sig_regions$start <- sig_regions$start - 100000  # for visualization
sig_regions$end <- sig_regions$end + 100000  # for visualization

genome_gr <- GRanges(
  seqnames = Rle(genome$chr),
  ranges = IRanges(start = genome$start, end = genome$end),
  LG = genome$LG)

sig_regions_gr <- GRanges(
  seqnames = Rle(sig_regions$chr),
  ranges = IRanges(start = sig_regions$start, end = sig_regions$end),
  module = sig_regions$module)

combined_gr <- c(genome_gr, sig_regions_gr)

ggbio::autoplot(combined_gr,layout = "karyogram", aes(color=module,fill=module)) +
  theme_void() +
  scale_fill_manual(values = colors[unique(MEtraitCor$module) %in% unique(sig_regions$module)], na.value = "coral4") +
  scale_color_manual(values = colors[unique(MEtraitCor$module) %in% unique(sig_regions$module)], na.value = "black") +
  coord_flip() +
  facet_wrap(~seqnames, nrow = 1) +
  theme(strip.text = element_text(angle = 90), legend.position = "none")

```